<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \AHT\SaleAgent\Block\SaleAgent $block */
?>
<?php $_orders = $block->getProductCollectionFactory(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Products Name')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('SKU')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Url to the product')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Commission type')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Commission value')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product name')) ?>" class="col id"><?= $block->escapeHtml($_order->getData('name')) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>" class="col date"><?= /* @noEscape */ $block->escapeHtml($_order->getData('sku')) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Url to the product')) ?>" class="col shipping">
                            <a href="<?= $block->escapeHtml($_order->getProductUrl()) ?>">
                                <span><?= $block->escapeHtml($_order->getData('name')) ?></span>
                            </a>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Commission type')) ?>" class="col total"><?= /* @noEscape */ $block->escapeHtml($_order->getData('commission_type')) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Commission value')) ?>" class="col status"><?= $block->escapeHtml($_order->getData('commission_value')) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>
