<?php 

$slidesToShow = $block->getData('slidetoshow');
$slidesToScroll = $block->getData('slidetoscroll');
$items = $block->getDataBlocks()->setPageSize($slidesToScroll);
echo $block->getHelper()['helper'];
echo $block->getHelper()['display_test'];

?>
<div class="products wrapper grid products-grid">
    <div class="products list items product-items my-list">
        <?php foreach($items->getData() as $item):  ?>
            <?php $imagePath = $block->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'aht/post/' . $item['image'];
            ?>
            <div class="item product product-item">
                <div class="product-item-info" data-container="product-grid">
                    <a href="<?php echo $block->getUrl('widget/index/detail').'ui_id/'.$item['ui_id']; ?>" class="product photo product-item-photo"
                        tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img class="product-image-photo"
                                src="<?php echo $imagePath  ?>"
                                max-width="240" max-height="300" alt="Name of product">
                            </span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php echo $block->getUrl('widget/index/detail').'ui_id/'.$item['ui_id']; ?>">
                                <?php echo $item['name'] ?> </a>
                        </strong>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="436"
                            data-price-box="product-id-436">
                            <span class="normal-price">
                                <span class="price-container price-final_price tax weee">
                                    <span class="price-label">Thể loại</span>
                                    <span id="product-price-436" data-price-amount="45" data-price-type="finalPrice"
                                    class="price-wrapper "><span class="price"><?php echo $item['name'] ?></span></span>
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'slick'], function($){
        $(function(){
            $('.my-list').slick({
                infinite: true,
                slidesToShow: 3,
            });
        });
    });
</script>